### ISSUE TITLE
The README should be entirely (or 99.9%) Markdown

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#160]
I am not viewing the README on github. I am viewing it as a plain file on my computer. Everything should be readable and understandable in it without the need to render it.

**Comment by tmhughes1** [comment]
The only thing(s) not written in markdown are the table of contents and jump to top links. Would you like those just removed then?

**Comment by willkill07** [comment]
GitHub already supports built-in navigation of markdown files.

It's also possible to specify relative links to headers using this syntax:
`[displayed text](#your-header-here)` (assuming the header was "Your Header Here")

If you really want a Table of Contents, you can adhere to this ^

**Comment by tmhughes1** [comment]
Alright thank you!
