### ISSUE TITLE
GUI execution should happen automatically regardless of OS in use (Mac vs Linux)

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#163]
I should not have to specify which OS I am on. You can detect it.

**Comment by gabe2762** [comment]
OS Detection

- [ ]  Make SpellingBee.py detect OS

- [ ]  Corresponding file runs depending on which OS was detected

- [ ] Excludes CLI version of the game

 Could even link or reference other tasks!

Primary: @gabe2762 

Secondary: @mention

Size: M

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)
