### ISSUE TITLE
Word List

### ISSUE THREAD

**Issue by tmhughes1** [mucsci-students/2023sp-420-MediaTek#17]
``
 Word List
 
 - [x] add json file to python file
 - [x] use a data structure to create the word list split into pangrams and 4+ letter words
 - [x] use the pangram list for base word generation

 - Primary: Devon
 - Secondary: Rest of team
 - Size: L
 - Actual Size: M
 - Actual Time: 2 hours
``

**Comment by auanmu** [comment]
Devon uploaded the file to #rough-draft-coding
