### ISSUE TITLE
GUI: Textbox should restrict input to valid characters only

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#170]
I can type anything in the textbox

**Comment by auanmu** [comment]
Works in windows version, mac version just needs to get updated @gabe2762

**Comment by willkill07** [comment]
There should be zero functionality difference across any OS

**Comment by auanmu** [comment]
> There should be zero functionality difference across any OS

We are going to try to make it one file, the issue we're running into is the GUI looks fine on windows with the changes, however it ruins how the mac version is (buttons out of place  etc). We have a separate file for MAC that just has changes visually to it looks nice. They are suppose to have all the same functions however the MAC version is missing some of the functions created.

**Comment by gabe2762** [comment]
Textbox Restrictions Across OS's

- [ ] Only valid letters allowed in input

- [ ] Active across OS's

Primary: @gabe2762 

Size: s

Actual Size: s

Actual Time: ~30 minutes
