### ISSUE TITLE
GUI: Loading from a file causes the points and Rank to be presented in a small font size

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#172]

**Comment by gabe2762** [comment]
Fix small font 

- [ ]  Changed the loaded font size to be consistent with the font size that is used when generating new puzzles, etc.

 Could even link or reference other tasks!

Primary: @gabe2762 

Secondary: @mention

Size: S

Actual Size: S

Actual Time: 10 minutes
