### ISSUE TITLE
General: Need more specific reasons as to why the word isn't valid

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#173]
It just says invalid. It should mention one of the three (in the following order):

- word length too small
- doesn't contain center letter
- word not in list

**Comment by gabe2762** [comment]
Specific Invalid Word Reasons

- [ ]  Word length too small
- [ ] Guess did not use required letter
- [ ]  Word not in list
- [ ] Maybe others

 Could even link or reference other tasks!

Primary: @gabe2762 

Secondary: @mention

Size: S/M

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)
