### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by gabe2762** [mucsci-students/2023sp-420-MediaTek#65]
``
GUI

- [x]  Create a graphical interface that supports all of sprint 1 functions.

- [x]  Allow player to type letters and click letters if they choose to. Allow players to delete any letters that have been entered.

- [x]  Selection task: Once GUI is done, then Selection task can be fully tested and completed.

Primary: Noah/Tess/Austin

Secondary: Gabe

Size: L

Actual Size: XL

Actual Time: 5+ hours
``

**Comment by gabe2762** [comment]
Likely to be broken into smaller tasks in order to fully implement all of sprint 1's tasks.

**Comment by auanmu** [comment]
I've made a little test file for you guys to look
