### ISSUE TITLE
Save/Load

### ISSUE THREAD

**Issue by gabe2762** [mucsci-students/2023sp-420-MediaTek#66]
``
Save/Load

- [x]  Allow saving with a standard JSON format that is used across all teams.

- [x]  Must ensure that a player can save a puzzle from our game and load it on a different team's application, and vice versa.

- [x]  This will build off of the already implemented Save/Load function, and will be linked across all teams Save/Load functions too.
- [x] Create save/load to work with GUI window box because windows automatically appends json

Primary: Devon

Secondary: Noah, Austin (Updated save/load to work with MU 420's std json format)

Size: M

Actual Size: TBD

Actual Time: TBD
``

**Comment by gabe2762** [comment]
Subject to change, will discuss with group.

**Comment by auanmu** [comment]
Got this to work in CLI, updated to work with 420's standard json format.
