### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by gabe2762** [mucsci-students/2023sp-420-MediaTek#67]
MVC

- [x]  Refactor code into MVC Model
- [x]  Extreme loss of mental sanity

Primary: Austin

Secondary: Tess, Noah, Devon, Gabe

Size: L

Actual Size: XXXL

Actual Time: 10-15 hours

**Comment by gabe2762** [comment]
Subject to change, will discuss with group.

**Comment by auanmu** [comment]
Believe it's finished
