### ISSUE TITLE
Input Method

### ISSUE THREAD

**Issue by gabe2762** [mucsci-students/2023sp-420-MediaTek#69]
``
Input Method

- [x]  Allow clicking or typing letters

- [x]  Allow backspace or clicking delete for letters

Primary: Noah

Secondary: Austin

Size: M

Actual Size: M

Actual Time: 2 hours
``

**Comment by auanmu** [comment]
Clicking, typing, backspace and clicking delete working

**Comment by auanmu** [comment]
Input method working fine

**Comment by auanmu** [comment]
adds user can only enter given letters for GUI
