### ISSUE TITLE
New Puzzle

### ISSUE THREAD

**Issue by gabe2762** [mucsci-students/2023sp-420-MediaTek#71]
``
New Puzzle

- [x]  Add a button to create a new puzzle

- [x]  If a puzzle is in progress prompt user to save current

Primary: Noah

Secondary: Austin, Gabe

Size: S

Actual Size: S

Actual Time: 1 hour
``

**Comment by auanmu** [comment]
Auto game working just fine, need to delete buttons though when pressed

**Comment by auanmu** [comment]
Base working as well, just need to add stuff like error checking and what not for the GUI

**Comment by auanmu** [comment]
New puzzle Auto and Base are working fine so far for the GUI. Once save function is working properly in GUI can update to ask user if they want to save if a puzzle is in progress.
